%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/hannessuhr/Documents/MATLAB/exactRaytracing/3D/LaCroixGlassData.xlsm
%    Worksheet: AllData
%
% Auto-generated by MATLAB on 17-Mar-2020 22:36:11

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 17);

% Specify sheet and range
opts.Sheet = "AllData";
opts.DataRange = "A2:Q358";

% Specify column names and types
opts.VariableNames = ["GlassType", "Var2", "Var3", "Mfg", "AbbeGroupings", "Var6", "nd1", "ne", "vd1", "ve", "Var11", "B1", "B2", "B3", "C1", "C2", "C3"];
opts.SelectedVariableNames = ["GlassType", "Mfg", "AbbeGroupings", "nd1", "ne", "vd1", "ve", "B1", "B2", "B3", "C1", "C2", "C3"];
opts.VariableTypes = ["string", "char", "char", "categorical", "categorical", "char", "double", "double", "double", "double", "char", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["GlassType", "Var2", "Var3", "Var6", "Var11"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["GlassType", "Var2", "Var3", "Mfg", "AbbeGroupings", "Var6", "Var11"], "EmptyFieldRule", "auto");

% Import the data
LaCroixGlassData = readtable("/Users/hannessuhr/Documents/MATLAB/exactRaytracing/3DexactRaytracing/LaCroixGlassData.xlsm", opts, "UseExcel", false);


%% Clear temporary variables
clear all;
load glassDB.mat

A = searchGlassDB("a","GlassType", glassDB);
BK7 = Glass.GlassFromDB(A(1,:))


